name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with:
          ref: develop
          node-version: '14.6.0'

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push test image
        uses: docker/build-push-action@v2
        with:
          target: runner
          file: Dockerfile-test
          context: .
          push: true
          tags: provenanceio/frontend-quicksync:develop
          build-args: REACT_APP_ENV=test
